demo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^begin/$', views.begin, name='begin'),
	url(r'^intro/start/$', views.start_intro, name='start_intro'),
	url(r'^intro/submit/$', views.submit_intro, name='submit_intro'),
	url(r'^intro/view/$', views.view_intro, name='view_intro'),
	url(r'^intro/rubric/$', views.view_rubric, name='view_rubric'),

]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.landing, name='landing'),
]

info/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^about/$', views.aboutPage, name='about'),
	url(r'^privacy/$', views.privacyPage, name='privacy'),

]

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#url(r'^dashboard/reviewer/$', views.showReviewerDash, name='reviewer_dashboard'),
	# url(r'^dashboard/student/$', views.showStudentDash, name='student_dashboard'),
	url(r'^assign/$', views.assignSubmission, name='assign_submission'),
	url(r'^submission/(?P<submission_id>[0-9]+)/$', views.showSubmission, name='show_submission'),
	url(r'^submission/submit/(?P<submission_id>[0-9]+)/$', views.submitReview, name='submit_review'),
	url(r'^categories/$', views.showCategories, name='categories'),
	url(r'^apply/$', views.applyReviewer, name='apply'),
	url(r'^categories/(?P<category_id>[0-9]+)/$', views.showSubCategories, name='sub_categories'),
	url(r'^categories/subcategories/(?P<subcategory_id>[0-9]+)/$', views.showProjects, name='projects'),
	url(r'^categories/projects/(?P<project_id>[0-9]+)/$', views.projectDetail, name='project_detail'),
	url(r'^categories/projects/rubric/(?P<project_id>[0-9]+)/$', views.projectSpec, name='project_specs'),
	url(r'^categories/projects/submit/(?P<project_id>[0-9]+)/$', views.submitProject, name='submit_project'),

]

reviewme/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as global_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from home import views




urlpatterns = [
	url(r'^', include('home.urls', namespace="home")),
    url(r'^.well-known/acme-challenge/(?P<id>.*)$', global_views.letsencrypt),
    url(r'^{}/admin/'.format(settings.ADMIN_URL_PATH), admin.site.urls),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^demo/', include('demo.urls', namespace="demo")),
    url(r'^content/',include('projects.urls', namespace="projects")),
    url(r'^info/',include('info.urls', namespace="info")),
    url(r'^users/reset-password-done/$', auth_views.password_reset_done, {'template_name': 'users/password_reset_done.html'}, name="password_reset_done"),
    url(r'^password/reset-password-confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'template_name': 'users/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^password/reset-password-complete/$', auth_views.password_reset_complete, {'template_name': 'users/password_reset_complete.html'}, name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'reviewme.views.custom_404_view'
handler500 = 'reviewme.views.custom_500_view'

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^signup/$', views.signupUser, name='signup_user'),
	url(r'^login/$', views.loginUser, name='login_user'),
	url(r'^logout/$', views.logout_user, name='logout_user'),
	url(r'^verification-start/$', views.verification_start, name='verification_start'),
	url(r'^verification-confirm/(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?P<ver_code>[0-9a-zA-Z]{32})/$'
					, views.verification_confirm, name='verification_confirm'),
	url(r'^verification-complete/$', views.verification_complete, name='verification_complete'),
	url(r'^reset-password/$', auth_views.password_reset, {'template_name': 'users/password_reset_start.html'}, name='password_reset_start'),
	url(r'^reset-password-done/$', auth_views.password_reset_done, {'template_name': 'users/password_reset_done.html'}, name="password_reset_done"),



]

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.conf import settings


# Create your views here.
def landing(request):
	return render(request, "home/index.html", {'media' : settings.MEDIA_URL})

home/templates/home/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>ReviewMe</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/helper.css' %}">
  {% if DEBUG %}

  {% else %}
      <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
        heap.load("3661075749");
  </script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74454041-4', 'auto');
  ga('send', 'pageview');
  </script>
  {% endif %}
  </head>
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'home:landing' %}" class="brand-logo"><i class="material-icons left medium">assignment_turned_in</i>ReviewMe</a>
    {% if request.user.is_authenticated %}
      <ul class="right hide-on-med-and-down">
        <li><a class="flow-text" href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a class="flow-text" href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="right hide-on-med-and-down">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
    {% if request.user.is_authenticated %}
      <ul class="side-nav" id="nav-mobile">
        <li><a href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a  href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="side-nav" id="nav-mobile">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center deep-orange-text">ReviewMe</h1>
      <div class="row center">
        <h5 class="header col s12 light">A place to learn by building and getting personalised feedback for projects.</h5>
      </div>
      <div class="row center margin-top-50 ">
        <div class="col s12 m6 push-m1">
          <a href="{% url 'projects:categories' %}" id="download-button" class="btn-large waves-effect waves-light deep-orange lighten-1 z-depth-3 margin-top-25">Get Started</a>
        </div>
        <div class="col s12 m6 pull-m1">
          <!-- <a href="{{ media }}samples/reviewme.pdf" target="_blank" id="download-button" class="btn-large waves-effect waves-light deep-orange lighten-1 z-depth-3 margin-top-25">View Sample Review</a> -->
          <a href="{% url 'demo:begin' %}" class="btn-large waves-effect waves-light deep-orange lighten-1 z-depth-3 margin-top-25">How It Works</a>
        </div>
      </div>
      <br><br>

    </div>
  </div>


  <div class="container margin-top-25">
    <div class="section">

      <div class="row">
        <div class="col s12 m12">
          <div class="icon-block center-align">
            <h2 class="center light-blue-text"><i class="material-icons large">description</i></h2>
            <h5 class="center-align">Complete a Project</h5>

            <p class="light flow-text">Our detailed objectives, specs and curated resources will help you become more confident as you build your way through our projects.</p>
          </div>
        </div>

        <div class="col s12 m12">
          <div class="icon-block center-align">
            <h2 class="center light-blue-text"><i class="material-icons large">cloud_upload</i></h2>
            <h5 class="center-align">Submit Your Project</h5>

            <p class="light flow-text">Check off that you’ve met all the requirements listed in the project rubric and submit, sit back and relax.
</p>
          </div>
        </div>

        <div class="col s12 m12">
          <div class="icon-block center-align">
            <h2 class="center light-blue-text"><i class="material-icons large">rate_review</i></h2>
            <h5 class="center-align">Reviews and Feedback</h5>

            <p class="light flow-text">Behind the scenes, one of our enthusiastic reviewers will check your project and give you personalised feedback to help you progress further as you learn new concepts and skills.</p>
          </div>
        </div>
      </div>

    </div>
    <br><br>

    <div class="section">

    </div>
  </div>

<footer class="page-footer transparent">
   <div class="footer-copyright deep-orange lighten-1">
     <div class="container">
       <div class="row">
         <div class="col s2 m2">
           <a href="{% url 'info:about' %}"><span class="grey-text text-lighten-5">About</span></a>
         </div>
         <div class="col s2 m2">
           <a href="{% url 'users:signup_user' %}"><span class="grey-text text-lighten-5">Register</span> </a>
         </div>
         <div class="col s2 m2">
           <a href="{% url 'info:privacy' %}"><span class="grey-text text-lighten-5">Privacy</span></a>
         </div>
         <div class="col s6 m4">
           <span class="grey-text text-lighten-5">© ReviewMe 2016</span>
         </div>
       </div>
     </div>
   </div>
 </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <script type="text/javascript" async>
    (function($){
  $(function(){

    $('.button-collapse').sideNav();

  }); // end of document ready
})(jQuery); // end of jQuery name space


   $(document).ready(function() {
    Materialize.updateTextFields();
  });

  </script>

  </body>
</html>