demo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^begin/$', views.begin, name='begin'),
	url(r'^intro/start/$', views.start_intro, name='start_intro'),
	url(r'^intro/submit/$', views.submit_intro, name='submit_intro'),
	url(r'^intro/view/$', views.view_intro, name='view_intro'),
	url(r'^intro/rubric/$', views.view_rubric, name='view_rubric'),

]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.landing, name='landing'),
]

info/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^about/$', views.aboutPage, name='about'),
	url(r'^privacy/$', views.privacyPage, name='privacy'),

]

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#url(r'^dashboard/reviewer/$', views.showReviewerDash, name='reviewer_dashboard'),
	# url(r'^dashboard/student/$', views.showStudentDash, name='student_dashboard'),
	url(r'^assign/$', views.assignSubmission, name='assign_submission'),
	url(r'^submission/(?P<submission_id>[0-9]+)/$', views.showSubmission, name='show_submission'),
	url(r'^submission/submit/(?P<submission_id>[0-9]+)/$', views.submitReview, name='submit_review'),
	url(r'^categories/$', views.showCategories, name='categories'),
	url(r'^apply/$', views.applyReviewer, name='apply'),
	url(r'^categories/(?P<category_id>[0-9]+)/$', views.showSubCategories, name='sub_categories'),
	url(r'^categories/subcategories/(?P<subcategory_id>[0-9]+)/$', views.showProjects, name='projects'),
	url(r'^categories/projects/(?P<project_id>[0-9]+)/$', views.projectDetail, name='project_detail'),
	url(r'^categories/projects/rubric/(?P<project_id>[0-9]+)/$', views.projectSpec, name='project_specs'),
	url(r'^categories/projects/submit/(?P<project_id>[0-9]+)/$', views.submitProject, name='submit_project'),

]

reviewme/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as global_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from home import views




urlpatterns = [
	url(r'^', include('home.urls', namespace="home")),
    url(r'^.well-known/acme-challenge/(?P<id>.*)$', global_views.letsencrypt),
    url(r'^{}/admin/'.format(settings.ADMIN_URL_PATH), admin.site.urls),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^demo/', include('demo.urls', namespace="demo")),
    url(r'^content/',include('projects.urls', namespace="projects")),
    url(r'^info/',include('info.urls', namespace="info")),
    url(r'^users/reset-password-done/$', auth_views.password_reset_done, {'template_name': 'users/password_reset_done.html'}, name="password_reset_done"),
    url(r'^password/reset-password-confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'template_name': 'users/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^password/reset-password-complete/$', auth_views.password_reset_complete, {'template_name': 'users/password_reset_complete.html'}, name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'reviewme.views.custom_404_view'
handler500 = 'reviewme.views.custom_500_view'

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^signup/$', views.signupUser, name='signup_user'),
	url(r'^login/$', views.loginUser, name='login_user'),
	url(r'^logout/$', views.logout_user, name='logout_user'),
	url(r'^verification-start/$', views.verification_start, name='verification_start'),
	url(r'^verification-confirm/(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?P<ver_code>[0-9a-zA-Z]{32})/$'
					, views.verification_confirm, name='verification_confirm'),
	url(r'^verification-complete/$', views.verification_complete, name='verification_complete'),
	url(r'^reset-password/$', auth_views.password_reset, {'template_name': 'users/password_reset_start.html'}, name='password_reset_start'),
	url(r'^reset-password-done/$', auth_views.password_reset_done, {'template_name': 'users/password_reset_done.html'}, name="password_reset_done"),



]

demo/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


def review_directory_path(instance, filename):
		# file will be uploaded to MEDIA_ROOT/<userid>_review_<id>
		return 'intros/{0}/intro_review.zip'.format(instance.user.id)


# Create your models here.
class Intro(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	q_a = models.TextField(blank=False)
	q_b = models.TextField(blank=False)
	note = models.TextField(null=True, blank=True)
	feedback = models.TextField(null=True, blank=True)
	finished = models.BooleanField(default=False)
	reviewing = models.BooleanField(default=True)
	review_files = models.FileField(upload_to=review_directory_path, blank=True, null=True)


	def __unicode__(self):
		if self.finished:
			return self.user.get_username() + "  -  finished"
		else:
			return self.user.get_username() + "  -  not finished"

demo/views.py
from django.shortcuts import render
from projects.models import Project, Objective, Resource
from .models import Intro
from django.conf import settings
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import IntegrityError




# Create your views here.
def begin(request):
	context = {}
	context['media'] = settings.MEDIA_URL
	current_project = Project.objects.order_by('id').first()
	context['project'] = current_project
	context['status'] = "No"
	context['objectives'] = Objective.objects.filter(project=current_project)
	context['resources'] = Resource.objects.filter(project=current_project).order_by('id')
	return render(request, 'demo/step1.html', context)

def start_intro(request):
	#add redirect to view intro if user already has intro object
	if request.user.is_authenticated():
		user = User.objects.get(pk=request.user.id)
		try:
			user_intro = Intro.objects.get(user=user)
			context = {}
			context['intro'] = user_intro
			return render(request, 'demo/viewintro.html', context)
		except:
			return render(request, 'demo/startintro.html')
	return render(request, 'demo/startintro.html')

def submit_intro(request):
	if request.method == 'POST':
		if request.user.is_authenticated():
			user = User.objects.get(pk=request.user.id)
			if request.POST['goal'] == "" or request.POST['inspire'] == "":
				messages.add_message(request, messages.ERROR, 'Make sure that you have answered both the questions')
				return render(request, 'demo/startintro.html')
			try:
				user_intro = Intro(user=user, q_a=request.POST['goal'], q_b=request.POST['inspire'], note=request.POST['note'])
				user_intro.save()
			except IntegrityError as e:
				return render(request, 'demo/viewintro.html')
			except:
				messages.add_message(request, messages.ERROR, 'Make sure that you have answered both the questions')
				return render(request, 'demo/startintro.html')
			messages.add_message(request, messages.SUCCESS, 'Your project has been submitted.')
			return render(request, 'demo/viewintro.html')
		else:
			if request.POST['goal'] == "" or request.POST['inspire'] == "":
				messages.add_message(request, messages.ERROR, 'Make sure that you have answered both the questions')
				return render(request, 'demo/startintro.html')
			context = {}
			context['q_a'] = request.POST['goal']
			context['q_b'] = request.POST['inspire']
			context['note'] = request.POST['note']
			context['message'] = 'Thanks for filling up the project. Now signup to get the feedback'
			return render(request, 'users/signup.html', context)
	else:
		raise Http404()

def view_intro(request):
	if request.user.is_authenticated():
		user = User.objects.get(pk=request.user.id)
		try:
			user_intro = Intro.objects.get(user=user)
			context = {}
			context['intro'] = user_intro
			return render(request, 'demo/viewintro.html', context)
		except:
			return render(request, 'demo/startintro.html')
	else:
		raise Http404()

def view_rubric(request):
	return render(request, 'demo/rubric.html')

demo/templates/demo/startintro.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Hello, World!</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/helper.css' %}">
  <link rel="stylesheet" href="{% static 'projects/css/style.css' %}">
  {% if DEBUG %}

  {% else %}
      <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
        heap.load("3661075749");
  </script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74454041-4', 'auto');
  ga('send', 'pageview');
  </script>
  {% endif %}

  </head>
<body>
 <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'home:landing' %}" class="brand-logo"><i class="material-icons left medium">assignment_turned_in</i>ReviewMe</a>
    {% if request.user.is_authenticated %}
      <ul class="right hide-on-med-and-down">
        <li><a class="flow-text" href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a class="flow-text" href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="right hide-on-med-and-down">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
    {% if request.user.is_authenticated %}
      <ul class="side-nav" id="nav-mobile">
        <li><a href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a  href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="side-nav" id="nav-mobile">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <main>
       <div class="container margin-top-25">
       <div class="row left-align">
        <h2 class="thin">Hello, World!</h2>
      </div>
        <section id="cd-timeline" class="cd-container">
    <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
       <h5>Project Description</h5>
        <h5 class="flow-text"><blockquote class="blue-border">This is a quick project to get you right into using
        our platform. Here we will talk about your goals and how we can help you to acheive them. This will just take a minute to complete and you will get personalised
        feedback regarding your goals.</blockquote></h5>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

     <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
       <h5>Example</h5>
        <h5 class="flow-text"><blockquote class="blue-border">An example of the project is included below. Check it out:</blockquote></h5>
        <a href="http://hellomaggiema.github.io/HelloWorld/index.html" class="waves-effect waves-light btn" target="_blank">Example</a>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h5>Project Objectives</h2>
        <ol class="browser-default disc">
        <div class="col s12 m12">

            <li class="flow-text">Set your goals.</li>
            <li class="flow-text">Help us help you.</li>
            <li class="flow-text">Learn how to use the platform.</li>

        </div>
        </ol>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

     <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h5>Resources</h5>
        <h5 class="flow-text"><blockquote class="blue-border">Checkout the following resources that will help you with the background knowledge required to complete this project:</blockquote></h5>
        <ol class="browser-default disc">
         <div class="col s12 m12 break-word">
           <li class="flow-text"><a href="http://personalexcellence.co/blog/why-set-goals/" class="flow-text" target="_blank">Goal setting : An article that discusses the importance of goal setting. </a></li>
           <li class="flow-text"><a href="http://norvig.com/21-days.html" class="flow-text" target="_blank">Teach Yourself Programming in Ten Years : A great article about how to go about becoming a Programmer which is applicable to all kinds of skill acquisition.</a></li>
        </div>
        </ol>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->



    <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h5>Rubric</h5>
        <h5 class="flow-text"><blockquote class="blue-border">Have a look at the rubric. You must meet all the specifications in the rubric:</blockquote></h5>
        <a href="{% url 'demo:view_rubric' %}" class="waves-effect waves-light btn" target="_blank">Rubric</a>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->


<form id="submitForm" action="{% url 'demo:submit_intro' %}"  method="post">
                {% csrf_token %}

    <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h5>Optional message for reviewer</h5>
        <h5 class="flow-text"><blockquote class="blue-border">Leave an optional message for the reviewer. It can be something relevant to the project or just a hello: </blockquote></h5>
        <div class="row">
          <div class="input-field col s12 m12">
            <textarea id="icon_prefix2" name="note" class="materialize-textarea"></textarea>
            <label for="icon_prefix2">Message for the reviewer</label>
          </div>
        </div>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

     <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h5>Set your goals</h5>
        <h5 class="flow-text"><blockquote class="blue-border">Usually you have to upload the required files but for this quick  project just type in your answers </blockquote></h5>
        <div class="row">
          <div class="input-field col s12 m12">
            <textarea id="icon_prefix3" name="goal" class="materialize-textarea"></textarea>
            <label for="icon_prefix3">What are your learning goals ? </label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 m12">
            <textarea id="icon_prefix4" name="inspire" class="materialize-textarea"></textarea>
            <label for="icon_prefix4">What kind of projects would you like us to create for you on ReviewMe? </label>
          </div>
        </div>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->



  </section> <!-- cd-timeline -->
      <div class="row margin-top-25">
        <div class="col s12 m8">
            <div class="row">
              <div class="col s12 m12">

                  <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                  <i class="material-icons right">send</i>
                </button>

              </form>
              </div>
            </div>
        </div>
      </div>
    </div>
  </main>

<footer class="page-footer transparent">
   <div class="footer-copyright deep-orange lighten-1">
     <div class="container">
       <div class="row">
         <div class="col s2 m2">
           <a href="{% url 'info:about' %}"><span class="grey-text text-lighten-5">About</span></a>
         </div>
         <div class="col s2 m2">
           <a href="{% url 'users:signup_user' %}"><span class="grey-text text-lighten-5">Register</span> </a>
         </div>
         <div class="col s2 m2">
           <a href="{% url 'info:privacy' %}"><span class="grey-text text-lighten-5">Privacy</span></a>
         </div>
         <div class="col s6 m4">
           <span class="grey-text text-lighten-5">© ReviewMe 2016</span>
         </div>
       </div>
     </div>
   </div>
 </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <script src="{% static 'projects/js/projects.js' %}"></script>
  <script type="text/javascript" async>
    (function($){
  $(function(){

    $('.button-collapse').sideNav();

  }); // end of document ready
})(jQuery); // end of jQuery name space


   $(document).ready(function() {
    Materialize.updateTextFields();
  });

  </script>
  {% if messages %}
      {% for message in messages %}
      <script>Materialize.toast('{{ message }}', 4000, 'rounded deep-orange lighten-1 flow-text')</script>
      {% endfor %}
  </ul>
  {% endif %}

  </body>
</html>

demo/templates/demo/viewintro.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Hello, World!</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/helper.css' %}">
  <link rel="stylesheet" href="{% static 'projects/css/style.css' %}">
  {% if DEBUG %}

  {% else %}
      <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
        heap.load("3661075749");
  </script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74454041-4', 'auto');
  ga('send', 'pageview');
  </script>
  {% endif %}

  </head>
<body>
 <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'home:landing' %}" class="brand-logo"><i class="material-icons left medium">assignment_turned_in</i>ReviewMe</a>
    {% if request.user.is_authenticated %}
      <ul class="right hide-on-med-and-down">
        <li><a class="flow-text" href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a class="flow-text" href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="right hide-on-med-and-down">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
    {% if request.user.is_authenticated %}
      <ul class="side-nav" id="nav-mobile">
        <li><a href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a  href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="side-nav" id="nav-mobile">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <main>
       <div class="container margin-top-25">
       <div class="row left-align">
        <h2 class="thin">Hello, World!</h2>
      </div>
        <section id="cd-timeline" class="cd-container">
    <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

     <div class="cd-timeline-content">
       <h5>Project Description</h5>
        <h5 class="flow-text"><blockquote class="blue-border">This is a quick project to get you right into using
        our platform. Here we will talk about your goals and how we can help you to acheive them. This will just take a minute to complete and you will get personalised
        feedback regarding your goals.</blockquote></h5>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

     <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
       <h5>Example</h5>
        <h5 class="flow-text"><blockquote class="blue-border">An example of the project is included below. Check it out:</blockquote></h5>
        <a href="http://hellomaggiema.github.io/HelloWorld/index.html" class="waves-effect waves-light btn" target="_blank">Example</a>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
        <h5>Project Objectives</h2>
        <ol class="browser-default disc">
        <div class="col s12 m12">

            <li class="flow-text">Set your goals.</li>
            <li class="flow-text">Help us help you.</li>
            <li class="flow-text">Learn how to use the platform.</li>

        </div>
        </ol>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

     <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

       <div class="cd-timeline-content">
        <h5>Resources</h5>
        <h5 class="flow-text"><blockquote class="blue-border">Checkout the following resources that will help you with the background knowledge required to complete this project:</blockquote></h5>
        <ol class="browser-default disc">
         <div class="col s12 m12 break-word">
           <li class="flow-text"><a href="http://personalexcellence.co/blog/why-set-goals/" class="flow-text" target="_blank">Goal setting : An article that discusses the importance of goal setting. </a></li>
           <li class="flow-text"><a href="http://norvig.com/21-days.html" class="flow-text" target="_blank">Teach Yourself Programming in Ten Years : A great article about how to go about becoming a Programmer which is applicable to all kinds of skill acquisition.</a></li>
        </div>
        </ol>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->



    <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h5>Rubric</h5>
        <h5 class="flow-text"><blockquote class="blue-border">Have a look at the rubric. You must meet all the specifications in the rubric:</blockquote></h5>
        <a href="{% url 'demo:view_rubric' %}" class="waves-effect waves-light btn" target="_blank">Rubric</a>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

  {% if intro.finished %}
    <div class="cd-timeline-block">
      <div class="cd-timeline-img light-blue lighten-1">
      </div> <!-- cd-timeline-img -->

      <div class="cd-timeline-content">
        <h5>Reviews</h5>
        <h5 class="flow-text"><blockquote class="blue-border">You can access your past history from here:</blockquote></h5>
          <div class="row">
            <div class="col s12 m12">
              <a href="{{intro.review_files.url}}" class="waves-effect waves-light btn">
              Your first review</a>
              <h5 class="flow-text"> Reviewer Comment : {{intro.feedback}}</h5>
            </div>
          </div>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    {% endif %}

  </section> <!-- cd-timeline -->
      <div class="row margin-top-25">
        <div class="col s12 m8">
            <div class="row">
              <div class="col s12 m12">
              {% if intro.finished %}
                  <h5 class="flow-text">You have finished this project! Yay!</h5>

              {% else %}

                  <h5 class="flow-text">Your project is awaiting review!</h5>

              {% endif %}
              </div>
            </div>
        </div>
      </div>
    </div>
  </main>

<footer class="page-footer transparent">
   <div class="footer-copyright deep-orange lighten-1">
     <div class="container">
       <div class="row">
         <div class="col s2 m2">
           <a href="{% url 'info:about' %}"><span class="grey-text text-lighten-5">About</span></a>
         </div>
         <div class="col s2 m2">
           <a href="{% url 'users:signup_user' %}"><span class="grey-text text-lighten-5">Register</span> </a>
         </div>
         <div class="col s2 m2">
           <a href="{% url 'info:privacy' %}"><span class="grey-text text-lighten-5">Privacy</span></a>
         </div>
         <div class="col s6 m4">
           <span class="grey-text text-lighten-5">© ReviewMe 2016</span>
         </div>
       </div>
     </div>
   </div>
 </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <script src="{% static 'projects/js/projects.js' %}"></script>
  <script type="text/javascript" async>
    (function($){
  $(function(){

    $('.button-collapse').sideNav();

  }); // end of document ready
})(jQuery); // end of jQuery name space


   $(document).ready(function() {
    Materialize.updateTextFields();
  });

  </script>
  {% if messages %}
      {% for message in messages %}
      <script>Materialize.toast('{{ message }}', 4000, 'rounded teal lighten-1 flow-text')</script>
      {% endfor %}
  </ul>
  {% endif %}

  </body>
</html>