demo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^begin/$', views.begin, name='begin'),
	url(r'^intro/start/$', views.start_intro, name='start_intro'),
	url(r'^intro/submit/$', views.submit_intro, name='submit_intro'),
	url(r'^intro/view/$', views.view_intro, name='view_intro'),
	url(r'^intro/rubric/$', views.view_rubric, name='view_rubric'),

]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.landing, name='landing'),
]

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#url(r'^dashboard/reviewer/$', views.showReviewerDash, name='reviewer_dashboard'),
	# url(r'^dashboard/student/$', views.showStudentDash, name='student_dashboard'),
	url(r'^assign/$', views.assignSubmission, name='assign_submission'),
	url(r'^submission/(?P<submission_id>[0-9]+)/$', views.showSubmission, name='show_submission'),
	url(r'^submission/submit/(?P<submission_id>[0-9]+)/$', views.submitReview, name='submit_review'),
	url(r'^categories/$', views.showCategories, name='categories'),
	url(r'^apply/$', views.applyReviewer, name='apply'),
	url(r'^categories/(?P<category_id>[0-9]+)/$', views.showSubCategories, name='sub_categories'),
	url(r'^categories/subcategories/(?P<subcategory_id>[0-9]+)/$', views.showProjects, name='projects'),
	url(r'^categories/projects/(?P<project_id>[0-9]+)/$', views.projectDetail, name='project_detail'),
	url(r'^categories/projects/rubric/(?P<project_id>[0-9]+)/$', views.projectSpec, name='project_specs'),
	url(r'^categories/projects/submit/(?P<project_id>[0-9]+)/$', views.submitProject, name='submit_project'),

]

reviewme/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as global_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from home import views




urlpatterns = [
	url(r'^', include('home.urls', namespace="home")),
    url(r'^.well-known/acme-challenge/(?P<id>.*)$', global_views.letsencrypt),
    url(r'^{}/admin/'.format(settings.ADMIN_URL_PATH), admin.site.urls),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^demo/', include('demo.urls', namespace="demo")),
    url(r'^content/',include('projects.urls', namespace="projects")),
    url(r'^info/',include('info.urls', namespace="info")),
    url(r'^users/reset-password-done/$', auth_views.password_reset_done, {'template_name': 'users/password_reset_done.html'}, name="password_reset_done"),
    url(r'^password/reset-password-confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'template_name': 'users/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^password/reset-password-complete/$', auth_views.password_reset_complete, {'template_name': 'users/password_reset_complete.html'}, name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'reviewme.views.custom_404_view'
handler500 = 'reviewme.views.custom_500_view'

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^signup/$', views.signupUser, name='signup_user'),
	url(r'^login/$', views.loginUser, name='login_user'),
	url(r'^logout/$', views.logout_user, name='logout_user'),
	url(r'^verification-start/$', views.verification_start, name='verification_start'),
	url(r'^verification-confirm/(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?P<ver_code>[0-9a-zA-Z]{32})/$'
					, views.verification_confirm, name='verification_confirm'),
	url(r'^verification-complete/$', views.verification_complete, name='verification_complete'),
	url(r'^reset-password/$', auth_views.password_reset, {'template_name': 'users/password_reset_start.html'}, name='password_reset_start'),
	url(r'^reset-password-done/$', auth_views.password_reset_done, {'template_name': 'users/password_reset_done.html'}, name="password_reset_done"),



]

users/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
import uuid
from django.contrib.auth.models import User



#model to save the user verification code
# Create your models here.
class UserVerification(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	ver_code = models.CharField(max_length=32)

class UserName(User):
	class Meta:
		proxy = True

	def __unicode__(self):
		return self.get_full_name()

users/views.py
from django.shortcuts import render
from django.conf import settings

#auth related imports
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from demo.models import Intro

#imports for validation
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.db import IntegrityError

from django.http import HttpResponseRedirect,HttpResponse, Http404
from django.core.urlresolvers import reverse
import json
from .utils import *

#importing the models
from .models import UserVerification
from projects.models import Role
from django.utils.crypto import get_random_string





# Create your views here.
#method to signup the user and login at the same time
def signupUser(request):
	if request.method == "GET":
		return render(request, 'users/signup.html', {})
	if request.method == "POST":
		try: #checking the validity of first / last name
			first_name = request.POST['firstName']
			last_name = request.POST['lastName']
			if len(first_name) > 30 or len(first_name) < 2:
				raise ValidationError("Invalid length of first name")

			if len(last_name) > 30 or len(last_name) < 2:
				raise ValidationError("Invalid length of last name")

		    #checking the validity of email
			email = request.POST['email']
			validate_email(email)

		    #checking min pasword length
			password = request.POST['password']
			if len(password) < 6:
				raise ValidationError("Minimum password length should be 6")

		except (KeyError, ValidationError) as e:
			response = {'status' : 0, 'msg' : str(e)}
			return HttpResponse(json.dumps(response), content_type='application/json')

		response = {}

		try:
			user = User.objects.create_user(email, email, password)
			user.first_name = first_name
			user.last_name = last_name
			user.is_active = False
			user.save()

			user_role_obj = Role(user=user, student=True, reviewer=False)
			# role_list = request.POST.getlist('role')
			# if('1' in role_list):
			# 	user_role_obj.student = True
			# if('2' in role_list):
			# 	user_role_obj.reviewer = True

			user_role_obj.save()


			response = {'status' : 1}

			ver_key = get_random_string(32)
			user_ver_object = UserVerification(user=user, ver_code=ver_key)
			user_ver_object.save()
			user_uuid = user_ver_object.id

			ver_key_url = request.build_absolute_uri("/users/verification-confirm/")
			ver_key_url = ver_key_url + str(user_uuid) + ver_key

			emailHTML = generate_email_HTML(ver_key_url)

			send_confirmation_email(user.email, emailHTML)

		except IntegrityError:
			response = {'status' : 0, 'msg' : 'User with the entered email already exists'}
			return HttpResponse(json.dumps(response), content_type='application/json')

		except:
			response = {'status' : 0, 'msg' : 'Things just blew up. Contact us at manibatra2002@gmail.com'}
			return HttpResponse(json.dumps(response), content_type='application/json')

		try:
			new_intro = Intro(user=user, q_a=request.POST['q_a'], q_b=request.POST['q_b'], note=request.POST['note'])
			new_intro.save()
		except Exception as e:
			pass
	else:
		raise Http404()

	return HttpResponse(json.dumps(response), content_type='application/json')


#method to show a view indacting user to confirm
def verification_start(request):
	context = { 'text' : 'A confirmation email has been sent to your email address. Click on the confirmation '
	'link in your email to activate your account', 'heading' : 'confirm your email address' }
	return render(request, 'users/verification.html', context)

#view to show when user clicks the confirmation link
def verification_confirm(request, uuid, ver_code):
	user_ver_object = UserVerification.objects.get(id=uuid)
	if ver_code == user_ver_object.ver_code:
		user = user_ver_object.user
		user.is_active = True
		user.save()
		return HttpResponseRedirect(reverse("users:verification_complete"))

	else:
		raise Http404()
	return render(request, 'users/verification.html', context)

#method to complete the verification process
def verification_complete(request):
	context = { 'text' : 'Your email has been confirmed. You can now login and start using ReviewMe now.'
					, 'heading' : 'Email Address Confirmed' }
	return render(request, 'users/verification.html', context)

#method to login the user
def loginUser(request):
	if request.method == "GET":
		return render(request, 'users/login.html', {})
	if request.method == "POST":
		try: #checking the validity of email
			email = request.POST['email']
			validate_email(email)

		 	#checking the validity of password
			password = request.POST['password']
			if len(password) < 6:
				raise ValidationError("Minimum password length should be 6")

		except (KeyError, ValidationError) as e:
			response = {'status' : 0, 'msg' : str(e)}
			return HttpResponse(json.dumps(response), content_type='application/json')

		user = authenticate(username=email, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				response = {'status' : 1}
			else:
				response = {'status' : 2, 'msg' : 'Please confirm your email address to login'}
		else:
			response = {'status' : 0, 'msg' : 'Wrong email or password'}

	else:
		raise Http404()

	return HttpResponse(json.dumps(response), content_type='application/json')


#method to log the user out
def logout_user(request):
	logout(request)
	return HttpResponseRedirect(reverse('home:landing'))

users/templates/users/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Login</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
<!--   <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
 -->
  {% if DEBUG %}

  {% else %}
      <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
        heap.load("3661075749");
  </script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74454041-4', 'auto');
  ga('send', 'pageview');
  </script>
  {% endif %}
 </head>
<body>


  <div class="container">
  <div class="row">
    <div class="col s12 center-align">
        <h2><a href="{% url 'home:landing' %}">ReviewMe</a></h>
        <h2><a ReviewMe</h>
    </div>
  </div>
  <div class="row">
    <form class="col s12" id="loginForm" action="{% url 'users:login_user' %}">
    {% csrf_token %}
      <div class="row">
        <div class="input-field col s6 m4 offset-m4 offset-s3">
          <input id="email" type="email" class="validate" name="email">
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6 m4 offset-m4 offset-s3">
          <input id="password" type="password" class="validate" name="password">
          <label for="password">Password</label>
          <p class="right-align"><a href="{% url 'users:password_reset_start' %}" >Forgot Password?</a></p>
        </div>
      </div>

      <div class="row">
        <div class="col s6 m4 offset-m4 offset-s3">
         <button class="btn waves-effect waves-light" type="submit" name="action">Sign in
            <i class="material-icons right">send</i>
         </button>
        </div>
       </div>

        <div class="row">
          <div class="col s12">
              <p class="center-align"><a href="{% url 'users:signup_user' %}">Don't have an account? Sign Up</a></p>
          </div>
        </div>

    </form>
  </div>


  </div>



  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <script src="{% static 'users/js/login.js' %}"></script>
  <script type="text/javascript" async>
    (function($){
  $(function(){

    $('.button-collapse').sideNav();

  }); // end of document ready
})(jQuery); // end of jQuery name space

$(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });

   $(document).ready(function() {
    Materialize.updateTextFields();
  });

  </script>

  </body>
</html>

users/templates/users/password_reset_complete.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Complete</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
<!--   <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
 -->
  {% if DEBUG %}

  {% else %}
      <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
        heap.load("3661075749");
  </script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74454041-4', 'auto');
  ga('send', 'pageview');
  </script>
  {% endif %}
 </head>
<body>
 <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'home:landing' %}" class="brand-logo"><i class="material-icons left medium">assignment_turned_in</i>ReviewMe</a>
    {% if request.user.is_authenticated %}
      <ul class="right hide-on-med-and-down">
        <li><a class="flow-text" href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a class="flow-text" href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="right hide-on-med-and-down">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
    {% if request.user.is_authenticated %}
      <ul class="side-nav" id="nav-mobile">
        <li><a href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a  href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="side-nav" id="nav-mobile">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>


<main>
  <div class="container">
  <div class="row">
    <div class="col s12 center-align">
                <h2><a href="{% url 'home:landing' %}">ReviewMe</a></h2>
    </div>
  </div>
   <div class="row">
    <div class="col s12 center-align">
        <p class="flow-text">Your password has been set.  You may go ahead and log in now.</p>
    </div>
  </div>

  </div>
</main>



  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <script src="{% static 'users/js/login.js' %}"></script>


  </body>
</html>

users/templates/users/signup.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>SignUp</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <!--   <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  -->
  {% if DEBUG %}

  {% else %}
      <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
        heap.load("3661075749");
  </script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74454041-4', 'auto');
  ga('send', 'pageview');
  </script>
  {% endif %}
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col s12 center-align">
                  <h2><a href="{% url 'home:landing' %}">ReviewMe</a></h>
        </div>
      </div>
      <div class="row">
        <div class="col s12 center-align">
                  <h4 class="flow-text">{{message}}</h4>
        </div>
      </div>
      <div class="row">
        <form class="col s12" id="signupForm" action="{% url 'users:signup_user' %}">
          {% csrf_token %}
          {% if message %}
            <input type="hidden" name="q_a" value="{{q_a}}">
            <input type="hidden" name="q_b" value="{{q_b}}">
            <input type="hidden" name="note" value="{{note}}">
          {% endif %}
          <div class="row">
            <div class="input-field col s6 m4 offset-m4 offset-s3">
              <input id="first_name" type="text" class="validate" name="firstName">
              <label for="first_name">First Name</label>
            </div>
            <div class="input-field col s6 m4 offset-m4 offset-s3">
              <input id="last_name" type="text" class="validate" name="lastName">
              <label for="last_name">Last Name</label>
            </div>
            <div class="input-field col s6 m4 offset-m4 offset-s3">
              <input id="email" type="email" class="validate" name="email">
              <label for="email">Email</label>
            </div>
            <div class="input-field col s6 m4 offset-m4 offset-s3">
              <input id="password" type="password" class="validate" name="password">
              <label for="password">Password</label>
            </div>
          </div>
          <!-- <div class="row">
            <div class="input-field col s4 offset-s4">
              <select name="role" multiple>
                <option value="" disabled selected>Register As</option>
                <option value="1">Student</option>
                <option value="2">Reviewer</option>
              </select>
              <label>Register yourself as student/reviewer</label>
            </div>
          </div> -->
          <div class="row">
            <div class="col s6 m4 offset-m4 offset-s3">
              <button class="btn waves-effect waves-light" type="submit" name="action">Sign Up<i class="material-icons right">send</i>
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col s12">
              <p class="center-align"><a href="{% url 'users:login_user' %}">Already have an account? Sign In</a></p>
            </div>
          </div>
        </form>
      </div>
    </div>
    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    <script src="{% static 'users/js/login.js' %}"></script>
    <script type="text/javascript" async>
    $(document).ready(function() {
    $('select').material_select();
  });

    </script>
  </body>
</html>

users/templates/users/verification.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Verified</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
<!--   <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
 -->
  {% if DEBUG %}

  {% else %}
      <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
        heap.load("3661075749");
  </script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74454041-4', 'auto');
  ga('send', 'pageview');
  </script>
  {% endif %}
 </head>
<body>

 <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'home:landing' %}" class="brand-logo"><i class="material-icons left medium">assignment_turned_in</i>ReviewMe</a>
    {% if request.user.is_authenticated %}
      <ul class="right hide-on-med-and-down">
        <li><a class="flow-text" href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a class="flow-text" href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="right hide-on-med-and-down">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
    {% if request.user.is_authenticated %}
      <ul class="side-nav" id="nav-mobile">
        <li><a href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a  href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="side-nav" id="nav-mobile">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text">{{ heading|title }}</h1>
      <div class="row center">
        <h5 class="header col s12 light">{{ text }}</h5>
      </div>
      <br><br>

    </div>
  </div>
  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <script src="{% static 'users/js/login.js' %}"></script>
  <script type="text/javascript" async>
    (function($){
  $(function(){

    $('.button-collapse').sideNav();

  }); // end of document ready
})(jQuery); // end of jQuery name space

$(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });

   $(document).ready(function() {
    Materialize.updateTextFields();
  });

  </script>

  </body>
</html>