demo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^begin/$', views.begin, name='begin'),
	url(r'^intro/start/$', views.start_intro, name='start_intro'),
	url(r'^intro/submit/$', views.submit_intro, name='submit_intro'),
	url(r'^intro/view/$', views.view_intro, name='view_intro'),
	url(r'^intro/rubric/$', views.view_rubric, name='view_rubric'),

]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.landing, name='landing'),
]

info/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^about/$', views.aboutPage, name='about'),
	url(r'^privacy/$', views.privacyPage, name='privacy'),

]

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#url(r'^dashboard/reviewer/$', views.showReviewerDash, name='reviewer_dashboard'),
	# url(r'^dashboard/student/$', views.showStudentDash, name='student_dashboard'),
	url(r'^assign/$', views.assignSubmission, name='assign_submission'),
	url(r'^submission/(?P<submission_id>[0-9]+)/$', views.showSubmission, name='show_submission'),
	url(r'^submission/submit/(?P<submission_id>[0-9]+)/$', views.submitReview, name='submit_review'),
	url(r'^categories/$', views.showCategories, name='categories'),
	url(r'^apply/$', views.applyReviewer, name='apply'),
	url(r'^categories/(?P<category_id>[0-9]+)/$', views.showSubCategories, name='sub_categories'),
	url(r'^categories/subcategories/(?P<subcategory_id>[0-9]+)/$', views.showProjects, name='projects'),
	url(r'^categories/projects/(?P<project_id>[0-9]+)/$', views.projectDetail, name='project_detail'),
	url(r'^categories/projects/rubric/(?P<project_id>[0-9]+)/$', views.projectSpec, name='project_specs'),
	url(r'^categories/projects/submit/(?P<project_id>[0-9]+)/$', views.submitProject, name='submit_project'),

]

reviewme/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as global_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from home import views




urlpatterns = [
	url(r'^', include('home.urls', namespace="home")),
    url(r'^.well-known/acme-challenge/(?P<id>.*)$', global_views.letsencrypt),
    url(r'^{}/admin/'.format(settings.ADMIN_URL_PATH), admin.site.urls),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^demo/', include('demo.urls', namespace="demo")),
    url(r'^content/',include('projects.urls', namespace="projects")),
    url(r'^info/',include('info.urls', namespace="info")),
    url(r'^users/reset-password-done/$', auth_views.password_reset_done, {'template_name': 'users/password_reset_done.html'}, name="password_reset_done"),
    url(r'^password/reset-password-confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'template_name': 'users/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^password/reset-password-complete/$', auth_views.password_reset_complete, {'template_name': 'users/password_reset_complete.html'}, name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'reviewme.views.custom_404_view'
handler500 = 'reviewme.views.custom_500_view'

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^signup/$', views.signupUser, name='signup_user'),
	url(r'^login/$', views.loginUser, name='login_user'),
	url(r'^logout/$', views.logout_user, name='logout_user'),
	url(r'^verification-start/$', views.verification_start, name='verification_start'),
	url(r'^verification-confirm/(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?P<ver_code>[0-9a-zA-Z]{32})/$'
					, views.verification_confirm, name='verification_confirm'),
	url(r'^verification-complete/$', views.verification_complete, name='verification_complete'),
	url(r'^reset-password/$', auth_views.password_reset, {'template_name': 'users/password_reset_start.html'}, name='password_reset_start'),
	url(r'^reset-password-done/$', auth_views.password_reset_done, {'template_name': 'users/password_reset_done.html'}, name="password_reset_done"),



]

projects/views.py
from django.shortcuts import render
from .models import Category, SubCategory, Project, Submission, Reviewer, Role, Objective, Spec, Resource
from demo.models import Intro
from django.db.models import Count
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect,HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.contrib import messages
import datetime
from datetime import timedelta
from django.utils.timezone import utc
import json

# Create your views here.
def showCategories(request):
	context = {}
	all_categories = Category.objects.annotate(num_projects=Count('subcategory__project', distinct=True))
	context['type'] = 'categories'
	context['items'] = all_categories
	if request.user.is_authenticated():
		try:
			user = User.objects.get(pk=request.user.id)
			user_intro = Intro.objects.get(user=user)
			context['intro'] = user_intro
		except:
			pass
	return render(request, 'projects/categories.html', context)

def showSubCategories(request, category_id):
	context = {}
	all_sub_categories = SubCategory.objects.filter(category=category_id).annotate(num_projects=Count('project', distinct=True))
	context['type'] = 'subcategories'
	context['items'] = all_sub_categories
	return render(request, 'projects/categories.html', context)

def showProjects(request, subcategory_id):
	context = {}
	all_projects = Project.objects.filter(sub_category=subcategory_id).order_by('id')
	context['type'] = 'projects'
	context['items'] = all_projects
	if request.user.is_authenticated():
		current_user = User.objects.get(pk=request.user.id)
		finished_projects = Submission.objects.filter(student=current_user).filter(finished=True)
		awaiting_projects = Submission.objects.filter(student=current_user).filter(returned_on__isnull=True)
		resubmission_required = Submission.objects.filter(student=current_user).filter(returned_on__isnull=False).filter(finished=False).values(
			'project__name').annotate(count=Count('project', distinct=True))

		flag = 0

		for item in context['items']:
			flag = 0
			for dictionary in finished_projects:
				if item == dictionary.project:
					item.status = "Yes"
					flag = 1;
					break;
			if flag == 0:
				for dictionary in awaiting_projects:
					if item == dictionary.project:
						item.status ="Wait"
						flag = 1;
						break;
			if flag == 0:
				for dictionary in resubmission_required:
					if item.name == dictionary['project__name']:
						item.status ="Redo"
						break;

	return render(request, 'projects/categories.html', context)


def projectDetail(request, project_id):
	context = {}
	current_project = Project.objects.get(pk=project_id)
	context['project'] = current_project
	context['status'] = "No"
	context['objectives'] = Objective.objects.filter(project=current_project)
	context['resources'] = Resource.objects.filter(project=current_project).order_by('id')
	if request.user.is_authenticated():
		current_user = User.objects.get(pk=request.user.id)
		all_submissions = Submission.objects.filter(student=current_user).filter(project=current_project).filter(returned_on__isnull=False)
		if len(all_submissions) > 0:
			context['history'] = all_submissions
		finished_projects = Submission.objects.filter(student=current_user).filter(finished=True)
		awaiting_projects = Submission.objects.filter(student=current_user).filter(returned_on__isnull=True)
		resubmission_required = Submission.objects.filter(student=current_user).filter(returned_on__isnull=False).filter(finished=False).values(
			'project__name').annotate(count=Count('project', distinct=True))

		flag = 0

		for dictionary in finished_projects:
			if current_project == dictionary.project:
				context['status'] = "Yes"
				flag = 1;
				break;
		if flag == 0:
			for dictionary in awaiting_projects:
				if current_project == dictionary.project:
					context['status'] ="Wait"
					flag = 1;
					break;
		if flag == 0:
			for dictionary in resubmission_required:
				if current_project.name == dictionary['project__name']:
					context['status'] ="No"
					break;
	return render(request, 'projects/projectdetail.html', context)


def submitProject(request, project_id):
	if request.method == 'POST':
		if request.user.is_authenticated():
			project = Project.objects.get(pk=project_id)
			user = User.objects.get(pk=request.user.id)
			new_submission = Submission(project=project, student=user, notes=request.POST['notes'])
			try:
				new_submission.submitted_files = request.FILES['projectzip']
			except:
				messages.add_message(request, messages.ERROR, 'Oops you did not submit any file')
				return HttpResponseRedirect('/content/categories/projects/' + project_id)

			new_submission.save()
			messages.add_message(request, messages.SUCCESS, 'Your project has been submitted for review')
			return HttpResponseRedirect(reverse('projects:categories'))

		else:
			messages.add_message(request, messages.ERROR, 'You have to be logged in to submit a project.')
			return HttpResponseRedirect('/content/categories/projects/' + project_id)

		return HttpResponse(json.dumps(response), content_type='application/json')



def showReviewerDash(request):
	if request.user.is_authenticated():


		current_reviewer = User.objects.get(pk=request.user.id)

		#did the user applied to be a reivewer
		current_role = Role.objects.get(user=current_reviewer)

		if current_role.reviewer:
			#list all the availablel projects that the reviewer is eligible to review
			all_eligible_projects = Reviewer.objects.filter(user=current_reviewer).filter(training_complete=True).values_list('project__id', flat=True)
			projects_available = Submission.objects.filter(project__in=all_eligible_projects).exclude(student=current_reviewer).filter(reviewer__isnull=True).filter(returned_on__isnull=
				True).values('project__name', 'project__id', 'project__cost').annotate(count=Count('project'))

			context = {}
			context['available'] = projects_available

			#list all the submissions available to review

			#fist check if submission has been sitting for more than time limit
			#setting timedelta as 5 for a time cap of 4 hrs to review
			lapsed_submissions = Submission.objects.filter(finished=False).filter(reviewer=current_reviewer).filter(assigned_time__lt=
									(datetime.datetime.utcnow().replace(tzinfo=utc))-timedelta(hours=3, minutes=59))
			for submission in lapsed_submissions:
				submission.reviewer = None
				submission.assigned_time = None
				submission.save()


			#list all the submissions still eligible
			projects_assigned = Submission.objects.filter(reviewer=current_reviewer).values('project__name', 'id', 'assigned_time',
								'project__cost').filter(returned_on__isnull=True)
			for dictionary in projects_assigned:
				time_left = time_remaining(dictionary['assigned_time'])
				dictionary['time_remaining'] = time_left

			context['assigned'] = projects_assigned
			return render(request, 'projects/reviewerdash.html', context)
		else:
			context = {}
			context['heading'] = "Become a reviewer"
			context['message'] = "You have not yet applied to be a reviewer. You can do so by clicking the button below."
			context['button'] = True
			context['button_message'] = "Apply"
			context['button_url'] = "/content/apply"
			return render(request, 'message.html', context)
	else:
		return HttpResponseRedirect(reverse('users:login_user'))

def applyReviewer(request):
	current_user = User.objects.get(pk=request.user.id)

	current_role = Role.objects.get(user=current_user)

	current_role.reviewer=True
	current_role.save()
	context = {}
	context['heading'] = "Awesome"
	context['message'] = "Your application has been submitted. We will be in touch shortly."
	return render(request, 'message.html', context)

def time_remaining(assigned_time):
	dt = datetime.datetime.utcnow().replace(tzinfo=utc)  - assigned_time
	hours = dt.seconds/60/60
	return 4 - hours


def assignSubmission(request):
	if request.method == 'POST':
		if request.user.is_authenticated():
			current_reviewer = User.objects.get(pk=request.user.id)
			#checking if two submissions have been assigned to the reivewer and not finished
			currently_assigned = Submission.objects.filter(reviewer=current_reviewer).filter(returned_on__isnull=True)
			if len(currently_assigned) >= 2:
				messages.add_message(request, messages.ERROR, 'Assignment limit reached')
				return HttpResponseRedirect(reverse('projects:reviewer_dashboard'))
			else:
				#less than two submissions assigned, assign the project
				current_submissions = Submission.objects.filter(project__id=request.POST['project_id']).filter(reviewer__isnull=True).order_by('submitted_on')
				submission_to_assign = current_submissions[0]
				submission_to_assign.assigned_time = datetime.datetime.utcnow().replace(tzinfo=utc)
				submission_to_assign.reviewer = current_reviewer
				submission_to_assign.save()
				messages.add_message(request, messages.SUCCESS, 'You have been assigned the submission')
				return HttpResponseRedirect(reverse('projects:reviewer_dashboard'))
		else:
			return HttpResponseRedirect(reverse('users:login'))

	else:
		raise Http404()

#method to show the submission page to the reviewer
def showSubmission(request, submission_id):

	if request.user.is_authenticated():
		current_user = User.objects.get(pk=request.user.id)
		current_user_role = Role.objects.get(user=current_user)
		if current_user_role.reviewer:
			current_submission = Submission.objects.get(id=submission_id, reviewer=current_user)
			context = {}
			context['submission'] = current_submission
			current_student = current_submission.student

			all_submissions = Submission.objects.filter(student=current_student).filter(project=current_submission.project).filter(returned_on__isnull=False)
			if len(all_submissions) > 0:
				context['history'] = all_submissions

			return render(request, 'projects/submission.html' , context)
		else:
			raise Http404()
	else:
		raise Http404()


#method to submit review
def submitReview(request, submission_id):

projects/templates/projects/categories.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Topics</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/helper.css' %}">
    {% if DEBUG %}
    {% else %}
        <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
        heap.load("3661075749");
  </script>
      <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-74454041-4', 'auto');
      ga('send', 'pageview');
      </script>
    {% endif %}
  </head>
  <body>
   <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'home:landing' %}" class="brand-logo"><i class="material-icons left medium">assignment_turned_in</i>ReviewMe</a>
    {% if request.user.is_authenticated %}
      <ul class="right hide-on-med-and-down">
        <li><a class="flow-text" href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a class="flow-text" href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="right hide-on-med-and-down">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
    {% if request.user.is_authenticated %}
      <ul class="side-nav" id="nav-mobile">
        <li><a href="{% url 'projects:categories' %}">Projects</a></li>
<!--         <li><a href="">Reviwer Dashboard</a></li>
 -->        <li><a  href="{% url 'users:logout_user' %}">Log Out</a></li>
      </ul>
    {% else %}
      <ul class="side-nav" id="nav-mobile">
        <li><a  class="flow-text" href="{% url 'users:login_user' %}">Sign In</a></li>
      </ul>
    {% endif %}
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <main>
  <div class="container margin-top-25">
    <div class="row left-align">
      <div class="nav-wrapper grey lighten-5">
        {% if type == "categories" %}
          <a href="{% url 'projects:categories' %}" class="breadcrumb big current grey-text text-darken-4">Subjects</a>
          {% elif type == "subcategories" %}
          <a href="{% url 'projects:categories' %}" class="breadcrumb big thin grey-text">Subjects</a>
          {% with items|first as item %}
          <a href="#!" class="breadcrumb big current grey-text text-darken-4">{{item.category.name|title}}</a>
        {% endwith %}
      {% else %}
        <a href="{% url 'projects:categories' %}" class="breadcrumb big thin grey-text">Subjects</a>
        {% with items|first as item %}
        <a href="{% url 'projects:sub_categories' item.sub_category.id %}" class="breadcrumb big thin grey-text">{{item.sub_category.category.name|title}}</a>
        <a href="#!" class="breadcrumb big current grey-text text-darken-4">{{item.sub_category.name|title}}</a>
      {% endwith %}
    {% endif %}
  </div>
</div>
<div class="row margin-top-50">
  {% if type == "categories" %}
    <div class="col s12 m4">

      <div class="card teal lighten-5">
        <div class="card-content white-text category-description activator hover">
          {% if intro %}
          <a href="{% url 'demo:view_intro' %}">
          {% else %}
          <a href="{% url 'demo:start_intro' %}">
          {% endif %}
          <div class="col s10 full-height">
            <span class="card-title black-text text-lighte-2 flow-text activator hover">Hello, World!</span>
          </div>
          </a>
          <div class="col s2">
            <i class="material-icons activator black-text hover text-lighten-2 right">more_vert</i>
          </div>

          <!--               <p class="light-blue-text">{{ item.description }}</p>
        --></div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4 flow-text"><i class="material-icons right">close</i></span>
          <p><strong>Hello, World!</strong></p>
          <p>Learn how to use the platform! Fast!</p>
        </div>
        <div class="card-action white">
            {% if intro %}
              {% if intro.finished %}
                  <a href="{% url 'demo:view_intro' %}" class="teal-text make-block">Finished Project<i class="material-icons right">beenhere</i></a>
              {% else %}
                  <a href="{% url 'demo:view_intro' %}" class="amber-text make-block">Awaiting Review<i class="material-icons right">timer</i></a>
              {% endif %}

            {% else %}
              <a href="{% url 'demo:start_intro' %}" class="deep-orange-text make-block">Start<i class="material-icons right">trending_flat</i></a>
            {% endif %}
        </div>
      </div>
    </div>

  {% endif %}
  {% for item in items %}
    <div class="col s12 m4">
      {% if type == "categories" %}
      <div class="card light-blue lighten-5">
      {% elif type == "subcategories" %}
       <div class="card deep-orange lighten-5">
       {% else %}
       <div class="card teal lighten-5">
       {% endif %}
        <div class="card-content white-text category-description hover">
        {% if type == "categories" %}
          <a href="{% url 'projects:sub_categories' item.id %}">
        {% elif type == "subcategories" %}
        <a href="{% url 'projects:projects' item.id %}">
        {% else %}
        <a href="{% url 'projects:project_detail' item.id %}">
        {% endif %}
        <div class="col s10 full-height">
            <span class="card-title black-text text-lighten-1 flow-text activator hover">{{ item.name }}</span>
          </div>
        </a>
          <div class="col s2">
            <i class="material-icons activator black-text hover text-lighten-2 right">more_vert</i>
          </div>
          <!--               <p class="light-blue-text">{{ item.description }}</p>
        --></div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4 flow-text"><i class="material-icons right">close</i></span>
          <p><strong>{{ item.name }}</strong></p>
          <p>{{ item.description }}</p>
        </div>
        <div class="card-action white">
          {% if type == "categories" %}
            <a href="{% url 'projects:sub_categories' item.id %}" class="deep-orange-text make-block">{{item.num_projects}} Project{{item.num_projects|pluralize}}  Available</a>
            {% elif type == "subcategories" %}
            <a href="{% url 'projects:projects' item.id %}" class="deep-orange-text make-block">{{item.num_projects}} Project{{item.num_projects|pluralize}}  Available</a>
          {% else %}
            {% if item.status == "Yes" %}
              <a href="{% url 'projects:project_detail' item.id %}" class="teal-text make-block">Finished Project<i class="material-icons right">beenhere</i></a>
              {% elif item.status == "Wait" %}
              <a href="{% url 'projects:project_detail' item.id %}" class="amber-text make-block">Awaiting Review<i class="material-icons right">timer</i></a>
              {% elif item.status == "Redo" %}
              <a href="{% url 'projects:project_detail' item.id %}" class="red-text make-block">Resubmit<i class="material-icons right">assignment_late</i></a>
            {% else %}
              <a href="{% url 'projects:project_detail' item.id %}" class="deep-orange-text make-block">Start<i class="material-icons right">trending_flat</i></a>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}
</div>
</div>
</main>
<footer class="page-footer transparent">
<div class="footer-copyright deep-orange lighten-1">
  <div class="container">
    <div class="row">
      <div class="col s2 m2">
        <a href="{% url 'info:about' %}"><span class="grey-text text-lighten-5">About</span></a>
      </div>
      <div class="col s2 m2">
        <a href="{% url 'users:signup_user' %}"><span class="grey-text text-lighten-5">Register</span> </a>
      </div>
      <div class="col s2 m2">
        <a href="{% url 'info:privacy' %}"><span class="grey-text text-lighten-5">Privacy</span></a>
      </div>
      <div class="col s6 m4">
        <span class="grey-text text-lighten-5">© ReviewMe 2016</span>
      </div>
    </div>
  </div>
</div>
</footer>
<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
<script type="text/javascript" async>
(function($){
$(function(){
$('.button-collapse').sideNav();
}); // end of document ready
})(jQuery); // end of jQuery name space
$(document).ready(function() {
Materialize.updateTextFields();
});
$(".dropdown-button").dropdown();
// $("#beReviewer").on('click', function(e) {
//    $('#displayThis').text('Reviewer Dashboard')
// })
$("#beStudent").on('click', function(e) {
$('#displayThis').text('Student Dashboard')
})
</script>
{% if messages %}
{% for message in messages %}
  <script>Materialize.toast('{{ message }}', 4000, 'rounded teal')</script>
{% endfor %}
</ul>
{% endif %}
</body>
</html>